/* Stride: sneaker store
   Products, cart, wishlist, routing (#/shop, #/product/1, #/cart, #/checkout) and views. */
const shoe=(bg,up,ac,so,r=0)=>"data:image/svg+xml,"+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#fff"/><stop offset="1" stop-color="${bg}"/></linearGradient></defs><rect width="400" height="400" fill="url(#g)"/><ellipse cx="205" cy="322" rx="150" ry="11" fill="#000" opacity=".12"/><g transform="rotate(${r} 200 200)"><path d="M55 268q0 34 42 34h236q30 0 30-30v-12H55z" fill="${so}"/><path d="M68 264V192q0-22 26-24l54-3q26-1 42-22l20-24q10-12 30-2l36 32q26 24 66 32 24 5 24 40v43z" fill="${up}"/><path d="M68 264V192q0-22 24-24h22l8 96z" fill="${ac}"/><path d="M158 252q64-34 148-24" stroke="${ac}" stroke-width="10" fill="none" stroke-linecap="round"/><path d="M212 132l26 16M196 148l30 18M180 164l30 18" stroke="${ac}" stroke-width="6" stroke-linecap="round"/><path d="M55 268h308" stroke="#fff" stroke-width="4" opacity=".7"/></g></svg>`);
const P=[
{id:1,file:"https://lh3.googleusercontent.com/aida-public/AB6AXuBULtfUq2Yohu8oDWgdV3bJTnmBnRU-ZCfGObsZ_DDNhHee2J97DLsDPNSMsIPS_AtmE4oqwNI5x1k3qt_-C7kpXlbDLoc1gC661GClR-UETiXgjggPYZf7b84AxtawfeKkarD-b6Gx7lFf4_SzfrX-zcyF_9nxCxE3E1FAb2xZxT-XUIms3C_W1Eqi3dZqIBY8UpnBaw7Hpol9m7GDIO778vgB0WdPB1RK46i7-aEPeweIT2CyoZeFSg",name:"Stride CloudRunner",tag:"Road Running",sub:"Men's & Women's",d:"Max responsive foam for long-haul stability.",price:120,cat:"Running",img:shoe("#e7eeff","#ffffff","#2563eb","#dbe1ff")},
{id:2,file:"https://lh3.googleusercontent.com/aida-public/AB6AXuBKxlP51P2Q5VH5L1gXwJHAv3XCqn3pA1YB2qQJ4-TSVCc3oPdE0t5_iTOx8f13FWIyIvPmW2uITXjOoBqIFPjZGHMiCIH2d4rIHjK3P9Fp6N0mPLaK0JzkO-YAeu5WWO_ijGcAFR1ysAxjwjSkgM-lyzAo2okf3EghK6PfwJxIUODXZazvFoWPUrMZaG3lzUrBz4GoUkp1nhybOtVgJFMjIHgOxin1jZYb2qTqsXPU5qWCDgkNtMGaVA",name:"Aero Glide 2",tag:"All-Day Comfort",sub:"Lifestyle & Walking",d:"Featherlight heel cup with memory foam insert.",price:95,cat:"Walking",img:shoe("#f0f3ff","#f5f5f0","#7a8fb8","#d8e3fb")},
{id:3,file:"https://lh3.googleusercontent.com/aida-public/AB6AXuDGP1d2oEhYwMvtGtbR6kZNQ5kvPLKUSRBl1tZJmLQZ__Xu1tJUuvu2VjLonWhVDnw9QLVuhpO_BcEflPBLL98KL0ffMcipNozmPKDBBPnyrtDzJKtepPO8nqlhDlGuRJjAK2HuH7-xTJXxFG-9P1jAB8nrSzpTy3ukTS2hbXRrMPBnnmNHgtsn2YooDFon1WoAPEO0eOXSpn2fs9V3Q67_3sSd7AcVrqmTzAwORjeDFmBRCYyC-4Wu5A",name:"Daily Pace Low",tag:"Lightweight Trainer",sub:"Performance Training",d:"Low-drop platform designed for sprint agility.",price:140,cat:"Training",img:shoe("#dee8ff","#c9cfd8","#1d4ed8","#ffffff")},
{id:4,file:"https://lh3.googleusercontent.com/aida-public/AB6AXuCRaiDX4U0uKqg4iEqODMOCbWdCx7sOavuKjZwosAqmKo8pBnmgUxWf4r1v3dab23q7OKSki70iwgGM1BfgWLaShIyS4fQqKtxaJhMgZ-I7q0CfTkiq63Y8EuU1G5jxvBt45dkTZ504YjmXB_d4eY8t8hji1rbKzqjnSbxgT6nULJBSAnvVLfjQsx197xz0eopInDbWuHFNsw8K8xmUVcM4FEdum0UfZxRJHzf4azZW42OvA4bnYYLlQg",name:"Sprint Knit",tag:"Road Running",sub:"Fast Tempo",d:"Seamless one-piece sockliner for frictionless fit.",price:110,cat:"Running",img:shoe("#e7eeff","#f9f9ff","#0047ab","#b4c5ff")},
{id:5,file:"https://lh3.googleusercontent.com/aida-public/AB6AXuAUxUEJ9tpTAz2QoJzB9vBGjgMwIVoKxe-RQAZD5K51FEBZEzbwCX46k29LPD-Eed8L0K2nZrN5WCFGm8bYP22XTMWOGUhM25f4xEwtmEJV3QFMn6mn96VMCJfSVnjN2kOu71HwdAr694ILZcWiiLtWHpLFWXoTbjjwqBXPcrg9Gdq8MNxUAEPktj1r5zqTrxdKqCm--eAwOLlYwnMohiUlh55Kq2vW_AGecDIHKnY843zaijKNkG3tCA",name:"Eco Breeze Trainer",tag:"Eco-Friendly",sub:"Everyday Walking",d:"Algae-blended EVA footbed with ultra-high rebound.",price:85,cat:"Walking",img:shoe("#fff1ea","#efe6d6","#7fb3e6","#d9c9a8")},
{id:6,file:"https://lh3.googleusercontent.com/aida-public/AB6AXuA2_6q51gIbDoldzQGTDCjWohNvFL1aqRBVQdlTFPTMdqIXL4Ii1v34ypRE6u8OtU0v5TAP7tzoeT4EG0HPZE-hkw4pwu0X78dUzODp3M9YIHJP9UuWSShxzzcu_GJvHSyAKk7OtxePHZijlHV3DUI2O-QpqA9lOeYkI-63SzA5fxbtXTSUlsBJvljMiUNnudajIV6B6A6DOatW2255LDdb6lplpdFiEKJ5Iur9ot5ObT9JtxYk-2vstg",name:"Trail Rover Light",tag:"All-Terrain",sub:"Trail & Gravel",d:"Multi-directional lugged outsole for wet-grip traction.",price:130,cat:"Trail",img:shoe("#e9eef7","#8a8f98","#2563eb","#3b3f46")}];
const HERO=shoe("#e7eeff","#ffffff","#2563eb","#b4c5ff",-10);
const FREE_AT=50,SHIP=8,CATS=["All","Running","Walking","Training","Trail"];

// state (saved in localStorage when available)
const store={get(k,f){try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
let cart=store.get("stride-cart",{}),wish=store.get("stride-wish",[]),cat="All",sort="featured";
Object.keys(cart).forEach(id=>{if(!P.some(p=>p.id==id))delete cart[id]});
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=n=>"$"+n.toFixed(2),count=()=>Object.values(cart).reduce((a,b)=>a+b,0);
const save=()=>{store.set("stride-cart",cart);store.set("stride-wish",wish)};
let tt;const toast=m=>{const t=$("#toast");t.textContent=m;t.style.opacity=1;clearTimeout(tt);tt=setTimeout(()=>t.style.opacity=0,1800)};

// inline SVG icons (replace the Google icon font so nothing can expire)
const IC={person:`<circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 4-6 8-6s8 2 8 6"/>`,shopping_cart:`<circle cx="9" cy="20" r="1.5"/><circle cx="18" cy="20" r="1.5"/><path d="M2 3h3l2.6 12h11l2-8H6"/>`,menu:`<path d="M4 6h16M4 12h16M4 18h16"/>`,add_shopping_cart:`<circle cx="9" cy="20" r="1.5"/><circle cx="18" cy="20" r="1.5"/><path d="M2 3h3l2.6 12h11l2-8H6M12 6v6M9 9h6"/>`,favorite:`<path d="M12 21s-8-5.2-8-11a4.5 4.5 0 0 1 8-2.8A4.5 4.5 0 0 1 20 10c0 5.800-8 11-8 11z"/>`,verified:`<circle cx="12" cy="12" r="9"/><path d="M8 12.500l3 3 5-6"/>`,local_shipping:`<path d="M2 6h11v10H2zM13 9h5l3 3v4h-8"/><circle cx="7" cy="18" r="1.800"/><circle cx="17" cy="18" r="1.800"/>`,published_with_changes:`<path d="M20 11a8 8 0 0 0-14-4M4 4v4h4M4 13a8 8 0 0 0 14 4M20 20v-4h-4"/>`,eco:`<path d="M5 19C5 9 11 4 20 4c0 9-5 15-15 15zM5 19l8-8"/>`,star:`<path d="M12 3l2.800 5.800 6.200.9-4.500 4.400 1.100 6.200L12 17.300l-5.600 3 1.100-6.200L3 9.700l6.200-.9z"/>`,arrow_forward:`<path d="M5 12h14M13 6l6 6-6 6"/>`,mail:`<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 7l9 6 9-6"/>`,remove:`<path d="M5 12h14"/>`,add:`<path d="M12 5v14M5 12h14"/>`};
function icons(){$$(".material-symbols-outlined:not([data-i])").forEach(el=>{const n=el.textContent.trim(),f=/'FILL' 1/.test(el.getAttribute("style")||"");el.dataset.i=1;el.removeAttribute("style");el.innerHTML=`<svg viewBox="0 0 24 24" width="1em" height="1em" fill="${f?"currentColor":"none"}" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${IC[n]||""}</svg>`})}

// if a photo link fails to load, fall back to the drawn version
addEventListener("error",e=>{const i=e.target;if(i.tagName=="IMG"&&i.dataset.fb){i.src=i.dataset.fb;delete i.dataset.fb}},true);

// views
const card=p=>{const w=wish.includes(p.id);return `<article class="group bg-surface-container-lowest rounded-xl shadow-sm overflow-hidden flex flex-col hover:shadow-md transition-shadow">
<div class="relative aspect-square bg-surface-container-low overflow-hidden"><a href="#/product/${p.id}" aria-label="View ${p.name}" class="block w-full h-full"><img src="${p.file}" data-fb="${p.img}" alt="${p.name}, ${p.tag.toLowerCase()} sneaker" loading="lazy" class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"/></a>
<span class="absolute top-3 left-3 px-2 py-0.5 rounded-full ${p.cat=="Walking"&&p.id==5?"bg-tertiary-fixed text-on-tertiary-fixed":"bg-surface-container-lowest/90 backdrop-blur-md"} text-label-md shadow-sm">${p.tag}</span>
<button data-wish="${p.id}" aria-pressed="${w}" aria-label="${w?"Remove from":"Add to"} wishlist: ${p.name}" class="absolute top-3 right-3 w-8 h-8 rounded-full bg-surface-container-lowest/90 backdrop-blur-md flex items-center justify-center ${w?"text-error":"text-on-surface-variant hover:text-error"}"><span class="material-symbols-outlined text-[18px]" style="font-variation-settings:'FILL' ${w?1:0}">favorite</span></button></div>
<div class="p-space-md flex flex-col flex-1 justify-between gap-space-sm"><div><span class="text-caption text-on-surface-variant">${p.sub}</span><h3 class="text-headline-sm"><a href="#/product/${p.id}" class="hover:text-primary">${p.name}</a></h3><p class="text-body-sm text-on-surface-variant">${p.d}</p></div>
<div class="pt-space-xs flex flex-col gap-space-sm"><span class="text-headline-sm">${money(p.price)}</span><div class="grid grid-cols-2 gap-space-xs"><button data-add="${p.id}" class="inline-flex items-center justify-center gap-1 px-3 py-2 rounded-lg bg-surface-container-low text-primary text-label-md hover:bg-surface-container-high transition-colors"><span class="material-symbols-outlined text-[16px]">add_shopping_cart</span>Add to Cart</button><button data-buy="${p.id}" class="px-3 py-2 rounded-lg bg-primary-container text-on-primary text-label-md hover:opacity-90 transition-opacity">Buy Now</button></div></div></div></article>`};
const wrap="w-full max-w-[1280px] mx-auto px-margin-mobile md:px-margin";
const grid=l=>`<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-gutter">${l.map(card).join("")}</div>`;

const home=()=>`<section class="${wrap} pt-space-lg pb-space-xl"><div class="overflow-hidden rounded-xl bg-surface-container-low shadow-sm"><div class="grid grid-cols-1 lg:grid-cols-12 items-center gap-space-lg p-space-lg md:p-space-xl">
<div class="lg:col-span-7 flex flex-col items-start gap-space-md"><div class="inline-flex items-center gap-space-xs px-3 py-1 rounded-full bg-surface-container-high text-primary text-label-md"><span class="w-2 h-2 rounded-full bg-primary"></span>New Season Collection 2026</div>
<h1 class="text-[32px] leading-10 md:text-display-lg tracking-tight max-w-xl font-bold">Step into comfort. Run with confidence.</h1>
<p class="text-body-lg text-on-surface-variant max-w-lg">Engineered for daily miles, casual walks, and everything in between. Lightweight cushioning built for all-day motion.</p>
<div class="flex flex-wrap gap-space-sm"><a href="#/shop" class="px-6 py-3 rounded-lg bg-primary-container text-on-primary text-label-lg shadow-sm hover:opacity-90">Shop Now</a><a href="#/shop" class="px-6 py-3 rounded-lg bg-surface-container-lowest text-label-lg shadow-sm hover:bg-surface-container">Explore New Arrivals</a></div>
<div class="flex items-center gap-space-sm text-on-surface-variant"><span class="material-symbols-outlined text-primary">verified</span><span class="text-body-sm">Over 40,000 runners powered daily</span></div></div>
<div class="lg:col-span-5 flex justify-center"><div class="relative w-full aspect-square max-w-[440px] rounded-xl overflow-hidden shadow-md"><img class="w-full h-full object-cover" alt="White and electric blue running sneaker" src="https://lh3.googleusercontent.com/aida-public/AB6AXuAH2YHzQ1O0tL8Gnun35gpgizm_z-8fBacEc3AYlxcBy2u2v_H7AEqkRouPQ_QNgr9BiILJWaWpolrHpn9Ezl6L_6xYf3VN-FFO-4Rj6aCL3W3awvyIlnWFZd3gkrRPWTXLKxGEasAA9qoVeTK-K_E2EWda0LgXfxMMkR-QPfU8VFIpM7_-c5EcsB78axG45LuxdKggZpaGaRA0Re6cvMrVVO5fzEdu9FCYzEAwQFHnXjZmx_XRCsG59g" data-fb="${HERO}"/>
<div class="absolute bottom-4 inset-x-4 p-3 rounded-lg bg-surface-container-lowest/90 backdrop-blur-md flex items-center justify-between"><div><span class="block text-label-md text-on-surface-variant">Featured Silhouette</span><span class="text-headline-sm">CloudRunner V1</span></div><span class="px-2.5 py-1 rounded-full bg-surface-container-high text-primary text-label-md">$120.00</span></div></div></div></div></div></section>
<section class="${wrap} pb-space-xl"><div class="grid grid-cols-1 md:grid-cols-3 gap-space-md">${[["local_shipping","Free Shipping over $"+FREE_AT,"Carbon-neutral delivery to your door within 2-3 business days."],["published_with_changes","30-Day Wear Test","Log real miles outside. Not satisfied? Return them with no fuss."],["eco","Sustainable Materials","Engineered uppers made with 75% recycled ocean-bound polyester."]].map(([i,t,d])=>`<div class="bg-surface-container-lowest p-space-lg rounded-xl shadow-sm flex gap-space-md"><div class="w-12 h-12 rounded-xl bg-surface-container-low flex items-center justify-center shrink-0 text-primary"><span class="material-symbols-outlined text-[28px]">${i}</span></div><div><h2 class="text-headline-sm">${t}</h2><p class="text-body-sm text-on-surface-variant">${d}</p></div></div>`).join("")}</div></section>
<section class="${wrap} pb-space-xl"><div class="flex flex-col md:flex-row md:items-end justify-between gap-space-sm mb-space-lg"><div><h2 class="text-headline-lg">Featured Sneakers</h2><p class="text-on-surface-variant">Hand-picked styles for your everyday rotation.</p></div><a href="#/shop" class="inline-flex items-center gap-1 text-label-lg text-primary hover:text-primary-container">View All (${P.length})<span class="material-symbols-outlined text-[18px]">arrow_forward</span></a></div>${grid(P)}</section>
<section class="${wrap} pb-space-xl"><div class="bg-surface-container-lowest rounded-xl p-space-lg shadow-sm flex flex-col md:flex-row items-center justify-between gap-space-lg"><div class="text-center md:text-left"><h3 class="text-headline-sm">Engineered for real runners</h3><p class="text-body-sm text-on-surface-variant">Rated 4.9 out of 5 across 12,000+ independent member reviews.</p></div><div class="flex items-center gap-space-lg"><div class="flex items-center gap-1" aria-label="4.9 stars">${"<span class='material-symbols-outlined text-secondary-container' style=\"font-variation-settings:'FILL' 1\">star</span>".repeat(5)}<span class="ml-2 text-headline-sm">4.9</span></div><div><span class="block text-headline-sm text-primary">100%</span><span class="text-caption text-on-surface-variant">Risk-Free Returns</span></div></div></div></section>
<section class="${wrap} pb-space-xl"><div class="rounded-xl bg-surface-container p-space-lg md:p-space-xl shadow-sm"><div class="max-w-2xl mx-auto text-center flex flex-col items-center gap-space-md"><div class="w-12 h-12 rounded-full bg-primary-container text-on-primary flex items-center justify-center"><span class="material-symbols-outlined">mail</span></div>
<h2 class="text-[32px] leading-10 md:text-display-lg tracking-tight font-bold">Join the Stride Club</h2><p class="text-body-lg text-on-surface-variant">Get <b class="text-primary">10% off</b> your first pair, early access to new releases, and weekly member running guides.</p>
${store.get("stride-sub",false)?ok():`<form id="sub" class="w-full max-w-md flex flex-col sm:flex-row gap-space-xs"><input required type="email" aria-label="Email address" placeholder="Enter your email address" class="flex-1 px-4 py-3 rounded-lg bg-surface-container-lowest text-body-sm shadow-sm placeholder:text-on-surface-variant/60"/><button class="px-6 py-3 rounded-lg bg-primary text-on-primary text-label-lg shadow-sm hover:opacity-90">Subscribe</button></form>`}
<span class="text-caption text-on-surface-variant">No spam, ever. Unsubscribe at any time.</span></div></div></section>`;
function ok(){return `<p class="text-label-md text-primary bg-surface-container-high px-4 py-2 rounded-full">Welcome to the club! Check your inbox for your 10% code.</p>`}

const shop=()=>{let l=P.filter(p=>cat=="All"||p.cat==cat);if(sort=="low")l=[...l].sort((a,b)=>a.price-b.price);if(sort=="high")l=[...l].sort((a,b)=>b.price-a.price);
return `<section class="${wrap} pt-space-lg pb-space-xl"><h1 class="text-headline-lg mb-space-xs">Shop all sneakers</h1><p class="text-on-surface-variant mb-space-lg">${l.length} ${l.length==1?"style":"styles"}${cat!="All"?" in "+cat:""}</p>
<div class="flex flex-col sm:flex-row sm:items-center justify-between gap-space-md mb-space-lg"><div class="flex flex-wrap gap-space-sm">${CATS.map(c=>`<button data-cat="${c}" aria-pressed="${c==cat}" class="px-4 py-2 rounded-full text-label-lg ${c==cat?"bg-primary text-on-primary":"bg-surface-container-lowest text-on-surface-variant hover:bg-surface-container-high"} shadow-sm">${c}</button>`).join("")}</div>
<label class="flex items-center gap-space-sm text-body-sm text-on-surface-variant">Sort by<select id="sort" class="px-3 py-2 rounded-lg bg-surface-container-lowest text-on-surface shadow-sm">${[["featured","Featured"],["low","Price: low to high"],["high","Price: high to low"]].map(([v,t])=>`<option value="${v}"${v==sort?" selected":""}>${t}</option>`).join("")}</select></label></div>${grid(l)}</section>`};

const cartView=()=>{const it=Object.entries(cart).map(([id,q])=>({p:P.find(x=>x.id==id),q}));
if(!it.length)return `<section class="${wrap} py-space-xl"><div class="bg-surface-container-lowest rounded-xl shadow-sm p-space-xl text-center flex flex-col items-center gap-space-md"><span class="material-symbols-outlined text-[48px] text-primary">shopping_cart</span><h1 class="text-headline-lg">Your cart is empty</h1><p class="text-on-surface-variant">Add a pair and it will show up here.</p><a href="#/shop" class="px-6 py-3 rounded-lg bg-primary-container text-on-primary text-label-lg">Browse sneakers</a></div></section>`;
const sub=it.reduce((a,{p,q})=>a+p.price*q,0),ship=sub>=FREE_AT?0:SHIP,left=FREE_AT-sub;
return `<section class="${wrap} pt-space-lg pb-space-xl"><h1 class="text-headline-lg mb-space-lg">Your cart (${count()})</h1><div class="grid grid-cols-1 lg:grid-cols-3 gap-gutter"><div class="lg:col-span-2 flex flex-col gap-space-md">${it.map(({p,q})=>`<div class="bg-surface-container-lowest rounded-xl shadow-sm p-space-md flex gap-space-md"><img src="${p.file}" data-fb="${p.img}" alt="${p.name}" class="w-24 h-24 rounded-lg object-cover shrink-0"/><div class="flex-1 flex flex-col justify-between gap-space-sm"><div class="flex justify-between gap-space-sm"><div><h2 class="text-headline-sm">${p.name}</h2><span class="text-caption text-on-surface-variant">${p.sub}</span></div><span class="text-headline-sm">${money(p.price*q)}</span></div>
<div class="flex items-center justify-between"><div class="flex items-center gap-space-sm"><button data-dec="${p.id}" aria-label="Decrease quantity of ${p.name}" class="w-8 h-8 rounded-full bg-surface-container-low hover:bg-surface-container-high flex items-center justify-center"><span class="material-symbols-outlined text-[18px]">remove</span></button><span class="w-6 text-center text-label-lg" aria-live="polite">${q}</span><button data-inc="${p.id}" aria-label="Increase quantity of ${p.name}" class="w-8 h-8 rounded-full bg-surface-container-low hover:bg-surface-container-high flex items-center justify-center"><span class="material-symbols-outlined text-[18px]">add</span></button></div>
<button data-rm="${p.id}" class="text-label-md text-on-surface-variant hover:text-error">Remove</button></div></div></div>`).join("")}</div>
<aside class="bg-surface-container-lowest rounded-xl shadow-sm p-space-lg h-fit flex flex-col gap-space-md"><h2 class="text-headline-sm">Order summary</h2>
<div class="text-body-sm ${left>0?"text-on-surface-variant":"text-primary"}">${left>0?`Add ${money(left)} more for free shipping.`:"You've unlocked free shipping."}<div class="mt-2 h-2 rounded-full bg-surface-container overflow-hidden"><div class="h-full bg-primary-container" style="width:${Math.min(100,sub/FREE_AT*100)}%"></div></div></div>
<div class="flex justify-between text-body-md"><span>Subtotal</span><span>${money(sub)}</span></div><div class="flex justify-between text-body-md"><span>Shipping</span><span>${ship?money(ship):"Free"}</span></div>
<div class="flex justify-between text-headline-sm pt-space-sm border-t border-outline-variant/50"><span>Total</span><span>${money(sub+ship)}</span></div>
<a href="#/checkout" class="text-center px-6 py-3 rounded-lg bg-primary-container text-on-primary text-label-lg hover:opacity-90">Checkout</a><a href="#/shop" class="text-center text-label-lg text-primary">Continue shopping</a></aside></div></section>`};

const totals=()=>{const sub=Object.entries(cart).reduce((a,[id,q])=>a+P.find(x=>x.id==id).price*q,0),ship=sub>=FREE_AT?0:SHIP;return{sub,ship,total:sub+ship}};
const wishlist=()=>{const l=P.filter(p=>wish.includes(p.id));return `<section class="${wrap} pt-space-lg pb-space-xl"><h1 class="text-headline-lg mb-space-lg">Wishlist (${l.length})</h1>${l.length?grid(l):`<div class="bg-surface-container-lowest rounded-xl shadow-sm p-space-xl text-center flex flex-col items-center gap-space-md"><span class="material-symbols-outlined text-[48px] text-primary">favorite</span><p class="text-on-surface-variant">Tap the heart on any sneaker to save it here.</p><a href="#/shop" class="px-6 py-3 rounded-lg bg-primary-container text-on-primary text-label-lg">Browse sneakers</a></div>`}</section>`};
const fld=(n,l,t="text")=>`<label class="flex flex-col gap-1 text-label-md text-on-surface-variant">${l}<input required name="${n}" type="${t}" class="px-4 py-3 rounded-lg bg-surface-container-low text-body-sm text-on-surface"/></label>`;
let order=null;
const checkout=()=>{if(!count())return cartView();const t=totals();return `<section class="${wrap} pt-space-lg pb-space-xl"><h1 class="text-headline-lg mb-space-lg">Checkout</h1><div class="grid grid-cols-1 lg:grid-cols-3 gap-gutter">
<form id="co" class="lg:col-span-2 bg-surface-container-lowest rounded-xl shadow-sm p-space-lg grid sm:grid-cols-2 gap-space-md"><h2 class="sm:col-span-2 text-headline-sm">Shipping details</h2>${fld("name","Full name")}${fld("email","Email","email")}<div class="sm:col-span-2 flex flex-col">${fld("address","Street address")}</div>${fld("city","City")}${fld("zip","Postal code")}<p class="sm:col-span-2 text-body-sm text-on-surface-variant">Demo store: no payment is taken and nothing is shipped.</p><button class="sm:col-span-2 px-6 py-3 rounded-lg bg-primary-container text-on-primary text-label-lg hover:opacity-90">Place order, ${money(t.total)}</button></form>
<aside class="bg-surface-container-lowest rounded-xl shadow-sm p-space-lg h-fit flex flex-col gap-space-sm"><h2 class="text-headline-sm">Your items</h2>${Object.entries(cart).map(([id,q])=>{const p=P.find(x=>x.id==id);return `<div class="flex justify-between text-body-sm"><span>${p.name} × ${q}</span><span>${money(p.price*q)}</span></div>`}).join("")}<div class="flex justify-between text-body-sm text-on-surface-variant"><span>Shipping</span><span>${t.ship?money(t.ship):"Free"}</span></div><div class="flex justify-between text-headline-sm pt-space-sm border-t border-outline-variant/50"><span>Total</span><span>${money(t.total)}</span></div><a href="#/cart" class="text-label-lg text-primary">Back to cart</a></aside></div></section>`};
const done=()=>!order?home():`<section class="${wrap} py-space-xl"><div class="bg-surface-container-lowest rounded-xl shadow-sm p-space-xl text-center flex flex-col items-center gap-space-md"><span class="material-symbols-outlined text-[48px] text-primary">verified</span><h1 class="text-headline-lg">Thanks, ${order.name}!</h1><p class="text-on-surface-variant">Order ${order.id} (${money(order.total)}) is confirmed. A receipt is on its way to ${order.email}.</p><a href="#/shop" class="px-6 py-3 rounded-lg bg-primary-container text-on-primary text-label-lg">Keep shopping</a></div></section>`;

const INFO={
1:{r:4.8,n:2431,b:["Max-cushion responsive foam absorbs impact on long road runs without feeling heavy.","Engineered mesh upper keeps your feet cool and locked in at any pace.","Wide, stable base and a firm heel counter add support when fatigue sets in.","Durable rubber outsole with flex grooves for smooth toe-offs on pavement."],s:[["Best for","Road running, daily training"],["Weight","248 g (men's size 9)"],["Heel drop","8 mm"],["Upper","Engineered mesh, 75% recycled polyester"],["Fit","True to size"]]},
2:{r:4.7,n:1876,b:["Featherlight heel cup with a memory foam insert cradles your heel all day.","Soft, breathable knit upper that moves with your foot.","Flexible cushioned sole built for errands, commuting and long walks.","Padded collar and pull tab make them easy to slip on and off."],s:[["Best for","Lifestyle, walking, travel"],["Weight","215 g (men's size 9)"],["Heel drop","6 mm"],["Upper","Stretch knit"],["Fit","True to size"]]},
3:{r:4.6,n:1342,b:["Low-drop platform keeps you close to the ground for quick, agile changes of direction.","Lightweight mesh upper with a royal blue heel counter for a locked-in feel.","Responsive midsole gives a snappy push-off for intervals and gym circuits.","Grippy outsole pattern handles studio floors, turf and track."],s:[["Best for","Gym training, intervals, sprints"],["Weight","236 g (men's size 9)"],["Heel drop","4 mm"],["Upper","Breathable mesh"],["Fit","True to size"]]},
4:{r:4.7,n:2104,b:["Seamless one-piece sockliner removes hot spots and rubbing for a frictionless fit.","Breathable engineered knit upper stretches where you need it.","Light, springy cushioning made for fast tempo runs.","Reflective details help you stay visible on early and late runs."],s:[["Best for","Tempo runs, race day"],["Weight","226 g (men's size 9)"],["Heel drop","7 mm"],["Upper","Engineered knit"],["Fit","Runs slightly snug, size up if between sizes"]]},
5:{r:4.5,n:987,b:["Algae-blended EVA footbed delivers high rebound with a lower environmental footprint.","Upper made from recycled materials in a light ecru and sky blue finish.","Cushioned, flexible build that stays comfortable on all-day walks.","Easy to pair with casual outfits or athleisure."],s:[["Best for","Everyday walking, casual wear"],["Weight","230 g (men's size 9)"],["Heel drop","6 mm"],["Upper","Recycled fabric blend"],["Fit","True to size"]]},
6:{r:4.8,n:1560,b:["Multi-directional lugged outsole bites into wet rock, mud and loose gravel.","Reinforced toe guard protects against rocks and roots.","Lightweight, breathable upper dries quickly after stream crossings.","Cushioned midsole smooths out rough terrain on long days out."],s:[["Best for","Trail, gravel, hiking"],["Weight","272 g (men's size 9)"],["Heel drop","8 mm"],["Upper","Ripstop mesh with toe guard"],["Fit","True to size"]]}};
const stars=r=>`<span class="inline-flex text-secondary-container" role="img" aria-label="${r} out of 5 stars">${"<span class='material-symbols-outlined text-[18px]' style=\"font-variation-settings:'FILL' 1\">star</span>".repeat(Math.round(r))}</span>`;
const product=()=>{const p=P.find(x=>x.id==location.hash.split("/")[2]);if(!p)return shop();const i=INFO[p.id],w=wish.includes(p.id);
return `<section class="${wrap} pt-space-lg pb-space-xl"><nav class="text-body-sm text-on-surface-variant mb-space-md"><a href="#/shop" class="text-primary hover:underline">Shop</a> / ${p.cat} / ${p.name}</nav>
<div class="grid grid-cols-1 lg:grid-cols-12 gap-gutter">
<div class="lg:col-span-5"><div class="aspect-square rounded-xl overflow-hidden bg-surface-container-lowest shadow-sm"><img src="${p.file}" data-fb="${p.img}" alt="${p.name}, ${p.tag.toLowerCase()} sneaker" class="w-full h-full object-cover"/></div></div>
<div class="lg:col-span-4 flex flex-col gap-space-sm"><span class="text-label-md text-primary">${p.tag}</span><h1 class="text-headline-lg">${p.name}</h1><p class="text-body-sm text-on-surface-variant">${p.sub}</p>
<div class="flex items-center gap-space-sm text-body-sm">${stars(i.r)}<b>${i.r}</b><span class="text-primary">${i.n.toLocaleString()} ratings</span></div>
<div class="border-t border-outline-variant/50 pt-space-sm"><span class="text-headline-lg">${money(p.price)}</span><span class="block text-caption text-on-surface-variant">Free delivery on orders over $${FREE_AT}.</span></div>
<h2 class="text-headline-sm pt-space-sm">About this item</h2><ul class="list-disc pl-5 flex flex-col gap-space-xs text-body-md text-on-surface-variant">${i.b.map(x=>`<li>${x}</li>`).join("")}</ul></div>
<aside class="lg:col-span-3 bg-surface-container-lowest rounded-xl shadow-sm p-space-lg h-fit flex flex-col gap-space-sm"><span class="text-headline-lg">${money(p.price)}</span><p class="text-body-sm text-on-surface-variant">Free delivery in 2-3 business days on orders over $${FREE_AT}.</p><p class="text-headline-sm text-primary">In stock</p>
<button data-add="${p.id}" class="px-4 py-3 rounded-full bg-surface-container-high text-primary text-label-lg hover:bg-surface-variant">Add to Cart</button><button data-buy="${p.id}" class="px-4 py-3 rounded-full bg-primary-container text-on-primary text-label-lg hover:opacity-90">Buy Now</button>
<button data-wish="${p.id}" aria-pressed="${w}" class="px-4 py-3 rounded-full ${w?"text-error":"text-on-surface-variant"} text-label-lg hover:bg-surface-container-low flex items-center justify-center gap-1"><span class="material-symbols-outlined text-[18px]"${w?` style="font-variation-settings:'FILL' 1"`:""}>favorite</span>${w?"Saved to wishlist":"Add to wishlist"}</button>
<p class="text-caption text-on-surface-variant pt-space-xs">30-day wear test: return them if you're not satisfied.</p></aside></div>
<h2 class="text-headline-sm mt-space-xl mb-space-sm">Product details</h2><div class="bg-surface-container-lowest rounded-xl shadow-sm overflow-hidden">${i.s.map(([k,v],n)=>`<div class="grid grid-cols-3 gap-space-md px-space-lg py-space-sm text-body-sm ${n%2?"":"bg-surface-container-low/60"}"><b>${k}</b><span class="col-span-2 text-on-surface-variant">${v}</span></div>`).join("")}</div></section>`};

// routing + nav
const views={home,shop,product,wishlist,cart:cartView,checkout,done},links=[["home","Home","#/"],["shop","Shop","#/shop"],["wishlist","Wishlist","#/wishlist"],["cart","Cart","#/cart"]];
const route=()=>{const r=location.hash.replace("#/","").split("?")[0].split("/")[0];return views[r]?r:"home"};
function nav(){const r=route()=="product"?"shop":route(),h=(m)=>links.map(([k,t,href])=>`<a href="${href}" ${k==r?'aria-current="page"':""} class="${m?"py-3":"px-space-md py-space-sm"} rounded-lg text-label-lg flex items-center gap-space-xs ${k==r?"bg-surface-container-high text-on-surface":"text-on-surface-variant hover:bg-surface-container-low hover:text-on-surface"}">${t}${k=="cart"?`<span data-badge class="px-1.5 py-0.5 rounded-full bg-primary-container text-on-primary-container text-label-md leading-none">${count()}</span>`:""}</a>`).join("");
$("#nav").innerHTML=h(0);$("#mobile-nav").innerHTML=h(1)}
function badge(){$$("[data-badge]").forEach(b=>b.textContent=count())}
function render(keep){const y=scrollY;$("#app").innerHTML=views[route()]();nav();badge();document.title=({home:"Stride | Everyday movement made effortless",shop:"Shop | Stride",cart:"Cart | Stride",wishlist:"Wishlist | Stride",checkout:"Checkout | Stride",done:"Order placed | Stride"})[route()];icons();scrollTo(0,keep?y:0)}
addEventListener("hashchange",()=>{$("#mobile-nav").classList.add("hidden");$("#mobile-nav").classList.remove("flex");$("#menu-btn").setAttribute("aria-expanded","false");render()});

// actions
document.addEventListener("click",e=>{const t=e.target.closest("button");if(!t)return;const d=t.dataset;
if(d.add){cart[d.add]=(cart[d.add]||0)+1;save();badge();nav();toast(P.find(p=>p.id==d.add).name+" added to cart")}
else if(d.buy){cart[d.buy]=(cart[d.buy]||0)+1;save();location.hash="#/checkout"}
else if(d.wish){const id=+d.wish;wish=wish.includes(id)?wish.filter(x=>x!=id):[...wish,id];save();render(1)}
else if(d.cat){cat=d.cat;render(1)}
else if(d.inc){cart[d.inc]++;save();render(1)}
else if(d.dec){cart[d.dec]>1?cart[d.dec]--:delete cart[d.dec];save();render(1)}
else if(d.rm){delete cart[d.rm];save();render(1)}
else if(t.id=="menu-btn"){const m=$("#mobile-nav"),o=m.classList.contains("hidden");m.classList.toggle("hidden",!o);m.classList.toggle("flex",o);t.setAttribute("aria-expanded",o)}});
document.addEventListener("change",e=>{if(e.target.id=="sort"){sort=e.target.value;render(1)}});
document.addEventListener("submit",e=>{if(e.target.id=="co"){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));order={id:"ST-"+Math.floor(10000+Math.random()*90000),name:f.name.split(" ")[0],email:f.email,total:totals().total};cart={};save();location.hash="#/done";return}if(e.target.id=="sub"){e.preventDefault();store.set("stride-sub",true);e.target.outerHTML=ok()}});
render();
